# permissions for end users to edit configmapsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: configmapsync-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: my-operator-sample
    app.kubernetes.io/part-of: my-operator-sample
    app.kubernetes.io/managed-by: kustomize
  name: configmapsync-editor-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - configmapsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - configmapsyncs/status
  verbs:
  - get
